[project]
name = "admin-app-runner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "nuitka>=2.5.7",
    "pyinstaller>=6.11.1",
    "pystray>=0.19.5",
    "tkeasygui>=1.0.16",
]
