name: Windows Build

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v4

            - name: Set up Python
              run: uv python install

            - name: Install dependencies
              run: uv sync

            - name: Activate venv and Build
              run: .\build.ps1

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: ./dist/